# Generated by Django 3.0.5 on 2020-04-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='descricao')),
                ('quantidade', models.IntegerField(verbose_name='quantidade')),
                ('valor_compra', models.FloatField(max_length=16, verbose_name='valor compra')),
                ('valor_venda', models.FloatField(max_length=15, verbose_name='valor venda')),
                ('status', models.CharField(max_length=15, verbose_name='valor venda')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ('descricao',),
            },
        ),
    ]
