# Generated by Django 3.0.5 on 2020-04-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20200416_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='status',
            field=models.CharField(max_length=15, verbose_name='status'),
        ),
    ]
