# Generated by Django 3.0.5 on 2020-04-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_auto_20200425_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='status',
        ),
        migrations.AddField(
            model_name='produto',
            name='_status',
            field=models.PositiveIntegerField(choices=[(1, 'INATIVO'), (2, 'ATIVO')], default=2, verbose_name='status'),
        ),
    ]
