# Generated by Django 3.0.5 on 2020-04-16 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0004_auto_20200414_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateField(blank=True, null=True, verbose_name='data da venda')),
                ('hora_venda', models.DateField(blank=True, null=True, verbose_name='hora venda')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='data de pagamento')),
                ('valor_total_venda', models.CharField(blank=True, max_length=15, null=True, verbose_name='valor total venda')),
                ('forma_pagamento', models.CharField(blank=True, max_length=10, null=True, verbose_name='forma de pagamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.Cliente', verbose_name='cliente')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.Funcionario', verbose_name='funcionario')),
            ],
        ),
    ]
