# Generated by Django 3.0.5 on 2020-04-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'ordering': ('data_venda',), 'verbose_name': 'venda', 'verbose_name_plural': 'vendas'},
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor_total_venda',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='valor total venda'),
        ),
    ]
