# Generated by Django 3.0.5 on 2020-04-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cnpj',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
