# Generated by Django 3.0.5 on 2020-04-14 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0001_initial'),
        ('pessoa', '0002_auto_20200412_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='nome')),
                ('cnpj', models.CharField(blank=True, db_index=True, max_length=15, null=True, unique=True, verbose_name='CNPJ')),
                ('cpf', models.CharField(blank=True, db_index=True, max_length=15, null=True, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('celular', models.CharField(blank=True, max_length=14, null=True, verbose_name='celular')),
                ('telefone', models.CharField(blank=True, max_length=11, null=True, verbose_name='telefone')),
                ('dataCadastro', models.DateField(verbose_name='Data de Cadastro')),
                ('local', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='local.Local', verbose_name='endereço')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='nome')),
                ('cnpj', models.CharField(blank=True, db_index=True, max_length=15, null=True, unique=True, verbose_name='CNPJ')),
                ('cpf', models.CharField(blank=True, db_index=True, max_length=15, null=True, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('celular', models.CharField(blank=True, max_length=14, null=True, verbose_name='celular')),
                ('telefone', models.CharField(blank=True, max_length=11, null=True, verbose_name='telefone')),
                ('dataCadastro', models.DateField(verbose_name='Data de Cadastro')),
                ('status', models.CharField(max_length=10, verbose_name='Status')),
                ('local', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='local.Local', verbose_name='endereço')),
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'fornecedores',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='nome')),
                ('cnpj', models.CharField(blank=True, db_index=True, max_length=15, null=True, unique=True, verbose_name='CNPJ')),
                ('cpf', models.CharField(blank=True, db_index=True, max_length=15, null=True, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('celular', models.CharField(blank=True, max_length=14, null=True, verbose_name='celular')),
                ('telefone', models.CharField(blank=True, max_length=11, null=True, verbose_name='telefone')),
                ('dataEntrada', models.DateField(blank=True, null=True, verbose_name='Data de Entrada')),
                ('dataSaida', models.DateField(blank=True, null=True, verbose_name='Data de Saida')),
                ('usuario', models.CharField(blank=True, max_length=30, null=True, verbose_name='Usuario')),
                ('senha', models.CharField(blank=True, max_length=30, null=True, verbose_name='Senha')),
                ('nivelAcesso', models.CharField(max_length=50, verbose_name='Nivel de Acesso')),
                ('status', models.CharField(max_length=10, verbose_name='Status')),
                ('local', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='local.Local', verbose_name='endereço')),
            ],
            options={
                'verbose_name': 'funcionario',
                'verbose_name_plural': 'funcionarios',
                'ordering': ('nome',),
            },
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
