# Generated by Django 3.0.5 on 2020-04-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_auto_20200414_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='dataCadastro',
            new_name='data_cadastro',
        ),
        migrations.RenameField(
            model_name='fornecedor',
            old_name='dataCadastro',
            new_name='data_cadastro',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='dataEntrada',
            new_name='data_entrada',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='dataSaida',
            new_name='data_saida',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='nivelAcesso',
            new_name='nivel_acesso',
        ),
    ]
