# Generated by Django 3.0.5 on 2020-04-18 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0005_auto_20200416_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='telefone',
        ),
    ]
