# Generated by Django 3.0.5 on 2020-04-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0006_auto_20200418_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='sexo'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='sexo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='sexo'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='sexo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='sexo'),
        ),
    ]
