# Generated by Django 3.0.5 on 2020-04-18 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0007_auto_20200418_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='sexo',
        ),
    ]
