# Generated by Django 3.0.5 on 2020-04-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0008_auto_20200418_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='_sexo',
            field=models.PositiveIntegerField(choices=[(1, 'MASCULINO'), (2, 'FEMININO')], default=1, verbose_name='tipo de mascote'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='_sexo',
            field=models.PositiveIntegerField(choices=[(1, 'MASCULINO'), (2, 'FEMININO')], default=1, verbose_name='tipo de mascote'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='_sexo',
            field=models.PositiveIntegerField(choices=[(1, 'MASCULINO'), (2, 'FEMININO')], default=1, verbose_name='tipo de mascote'),
        ),
    ]
