# Generated by Django 3.0.5 on 2020-04-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0009_auto_20200418_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='_sexo',
            field=models.PositiveIntegerField(choices=[(1, 'MASCULINO'), (2, 'FEMININO')], default=1, verbose_name='sexo'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='_sexo',
            field=models.PositiveIntegerField(choices=[(1, 'MASCULINO'), (2, 'FEMININO')], default=1, verbose_name='sexo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='_sexo',
            field=models.PositiveIntegerField(choices=[(1, 'MASCULINO'), (2, 'FEMININO')], default=1, verbose_name='sexo'),
        ),
    ]
