# Generated by Django 3.0.5 on 2020-04-25 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compra', '0001_initial'),
        ('produto', '0003_auto_20200425_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_item', models.IntegerField(verbose_name='quantidade do item')),
                ('valor_item', models.FloatField(default=0, max_length=15, verbose_name='valor do item')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.Compra', verbose_name='compra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.Produto', verbose_name='produto')),
            ],
        ),
    ]
