# Generated by Django 3.0.5 on 2020-04-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemVenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='qtd_item',
            field=models.IntegerField(verbose_name='quantidade item'),
        ),
    ]
