# Generated by Django 3.0.5 on 2020-04-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemVenda', '0002_auto_20200416_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='valor_item',
            field=models.FloatField(default=0, max_length=15, verbose_name='valor item'),
        ),
    ]
