# Generated by Django 3.0.5 on 2020-04-25 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0010_auto_20200421_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateField(blank=True, null=True, verbose_name='data da compra')),
                ('hora_compra', models.DateField(blank=True, null=True, verbose_name='hora da compra')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='data de pagamento')),
                ('valor_total_compra', models.CharField(blank=True, max_length=16, null=True, verbose_name='valor total da compra')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoa.Fornecedor', verbose_name='fornecedor')),
            ],
        ),
    ]
